- name: Build Android APK
  run: |
    echo "=== Building Android APK ==="
    
    # 查找并进入正确的目录
    if [ -d "android&quot ]; then
      cd android
    elif [ -d "app&quot ]; then
      cd app
    else
      echo "No android/app directory found"
      echo "Contents of current directory:"
      ls -la
      exit 1
    fi
    
    echo "Current directory: $(pwd)"
    echo "Contents: $(ls)"
    
    # 尝试构建
    if [ -f "gradlew&quot ]; then
      echo "Using gradlew..."
      ./gradlew assembleRelease
    else
      echo "No gradlew found"
      exit 1
    fi      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/yarn
          node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Install dependencies
      run: yarn install

    - name: Skip tests
      run: echo "Skipping tests - proceeding directly to build"

    - name: Build Android APK
      run: |
        cd android
        ./gradlew assembleRelease

    - name: Upload Android APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: android/app/build/outputs/apk/release/app-release.apk
